services:
  tinyRAG:
    image: tinyrag:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GRADIO_LISTEN=true
      - GRADIO_SERVER_PORT=8080
      - GRADIO_SERVER_NAME=0.0.0.0